[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "dirks-mac-studio.tail3436d8.ts.net"
serverPort = 8501
gatherUsageStats = false
